- name: Criando o diretório da aplicacao My-App
  file: path={{ item }} state=directory
  with_items:
    - /opt/my-app
    - /opt/my-app/logs
    - /opt/my-app/conf
  register: criando_diretorios

- name: Copiando o arquivo de deployment da app para o host
  template:
    src: app-v1.yml.j2
    dest: /opt/my-app/app-v1.yml
    owner: root
    group: root
    mode: 0644
  register: copiando_template

- name: Copiando o arquivo de service da app para o host
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'service_app.yml', dest: '/opt/my-app/service_app.yml' }
  register: copiando_service_file

- name: Criando o deployment da App Giropops
  shell: kubectl apply -f /opt/my-app/app-v1.yml
  register: deploy_app

- name: Criando o Service da App My-App
  shell: kubectl apply -f /opt/my-app/service_app.yml
  register: deploy_svc_app
